### ISSUE TITLE
FetchError('Unable to fetch URL from any source.', 'git://gitlab.gnome.org/GNOME/mobile-broadband-provider-info.git;protocol=https;branch=master')

### ISSUE THREAD

**Issue by mistyron** [MistySOM/rzg2l#14]
We are facing below fetch error during yocto build.
```
WARNING: mobile-broadband-provider-info-1_20201225-r0 do_fetch: Failed to fetch URL git://gitlab.gnome.org/GNOME/mobile-broadband-provider-info.git;protocol=https;branch=master, attempting MIRRORS if available
ERROR: mobile-broadband-provider-info-1_20201225-r0 do_fetch: Fetcher failure: Unable to find revision 90f3fe28aa25135b7e4a54a7816388913bfd4a2a in branch master even from upstream
ERROR: mobile-broadband-provider-info-1_20201225-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://gitlab.gnome.org/GNOME/mobile-broadband-provider-info.git;protocol=https;branch=master')
ERROR: Logfile of failure stored in: /home/yocto/rzg_vlp_v3.0.0/build/tmp/work/aarch64-poky-linux/mobile-broadband-provider-info/1_20201225-r0/temp/log.do_fetch.12614
ERROR: Task (/home/yocto/rzg_vlp_v3.0.0/build/../poky/meta/recipes-connectivity/mobile-broadband-provider-info/mobile-broadband-provider-info_git.bb:do_fetch) failed with exit code '1'
```

**Comment by mistyron** [comment]
1. start the container with `$ ./run.sh -c /tmp/yocto_cache -n` this will bring you to a dev shell inside the container and execute the following command:
`$ sed -i 's/branch=master/branch=main/g' /home/yocto/rzg_vlp_v3.0.0/poky/meta/recipes-connectivity/mobile-broadband-provider-info/mobile-broadband-provider-info_git.bb`
to do the update, it replaces `branch=master` with `branch=main` in the mobile-broadband-provider-info recipe file.
2. then execute the following to re-invoke the build:
`$ cd rzg_vlp_v3.0.0/ && source poky/oe-init-build-env && bitbake mistysom-image`

**Comment by matinlotfali** [comment]
The provided solution is not the correct way of fixing it.

It looks like we need to add a bbappend file in the meta-mistysom submodule which changes the master to the main branch. Without it, the image won't be built from scratch (without a cache).

@mistyron Do you agree?

**Comment by mistyron** [comment]
@matinlotfali the above work around was a way to make it work quickly, I have not invested time to research if a proper solution even is needed. It might not be needed anymore, do you have spare cycles to research it?

**Comment by matinlotfali** [comment]
I ran the master branch without a cache and I did not get an error.
