### ISSUE TITLE
Coral cam connector on MistySOM Carrier

### ISSUE THREAD

**Issue by mistyron** [MistySOM/rzg2l#23]
for record keeping only:
The camera connector on MistyCarrier is compatible with Google Ciral cam looks like this on the schematic:
![image](https://user-images.githubusercontent.com/94636867/235954455-4be11ef4-dfa5-42c2-bb05-ff50342b0689.png)
Mind that the connector is backwards/inverted on revA, i.e. the FPS that is supplied with the camera **MUST NOT** be used (it'll break the camera when powered on!), use an FPC that has the connectors exposed on the same side instead.

**Comment by matinlotfali** [comment]
Is this documented in the wiki?

**Comment by mistyron** [comment]
It's part of the [MistyCarrier design](https://github.com/MistySOM/wiki/blob/master/content/DesignFiles.md) files that acn downloaded from [here](https://remote.mistywest.io/download/mh11/designfiles/CARRIER_001_Rev_A.zip). We have not provided a separated image as seen above which is fine, I think.
